import threading
def countdown(n):
	while n > 0:
		n -= 1
COUNT=10000000
#countdown(COUNT)
t1 = threading.Thread(target=countdown,args=(COUNT//8,))
t2 = threading.Thread(target=countdown,args=(COUNT//8,))
t3 = threading.Thread(target=countdown,args=(COUNT//8,))
t4 = threading.Thread(target=countdown,args=(COUNT//8,))
t5 = threading.Thread(target=countdown,args=(COUNT//8,))
t6 = threading.Thread(target=countdown,args=(COUNT//8,))
t7 = threading.Thread(target=countdown,args=(COUNT//8,))
t8 = threading.Thread(target=countdown,args=(COUNT//8,))
t1.start()
t2.start()
t3.start()
t4.start()
t5.start()
t6.start()
t7.start()
t8.start()
t1.join()
t2.join()
t3.join()
t4.join()
t5.join()
t6.join()
t7.join()
t8.join()
