/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class callILENative */

#ifndef _Included_callILENative
#define _Included_callILENative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     callILENative
 * Method:    printString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_callILENative_printString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
