apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  namespace: samples
spec:
  replicas: 1
  selector:
    zname: mysql
  template:
    metadata:
      labels:
        zname: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
