11:
	JAVA_HOME=/qopensys/QIBM/ProdData/JavaVM/jdk11/64bit system -e "CRTBNDC PGM(GAVIN/INVOKE) SRCSTMF('/qopensys/home/zhanggan/worktemp/invokedemo/invokeile.c')"
80:
	JAVA_HOME=/qopensys/QIBM/ProdData/JavaVM/jdk80/64bit system -e "CRTBNDC PGM(GAVIN/INVOKE) SRCSTMF('/qopensys/home/zhanggan/worktemp/invokedemo/invokeile.c')"
run11:
	JAVA_HOME=/qopensys/QIBM/ProdData/JavaVM/jdk11/64bit system -e "call gavin/invoke parm('-cp .' 'QIBMHello' '64' '0')"
run80:
	JAVA_HOME=/qopensys/QIBM/ProdData/JavaVM/jdk80/64bit system "call gavin/invoke parm('-cp .' 'QIBMHello' '64' '0')"
clean:
	rm core* Snap* javacore* 
