/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Prog */

#ifndef _Included_Prog
#define _Included_Prog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Prog
 * Method:    f1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Prog_f1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
