/*
 * eyecatch.c
 *
 *  Created on: Dec 2, 2014
 *      Author: gavin
 */


#define J9MEMTAG_EYECATCHER_ALLOC_HEADER			0xB1234567
#define J9MEMTAG_EYECATCHER_ALLOC_FOOTER			0xB7654321
#define J9MEMTAG_EYECATCHER_FREED_HEADER			0xBADBAD67
#define J9MEMTAG_EYECATCHER_FREED_FOOTER			0xBADBAD21

#define J9_STR_(x) #x
#define J9_STR(x) J9_STR_(x)
#define J9_GET_CALLSITE() __FILE__ ":" J9_STR(__LINE__)
#define STR_(x) #x
#define STR(x) STR_(x)
#define CALLSITE() __FILE__ ":" STR(__LINE__)

void main(){
	int a = ~J9MEMTAG_EYECATCHER_ALLOC_HEADER;
	printf("J9MEMTAG_EYECATCHER_ALLOC_HEADER=%x,~J9MEMTAG_EYECATCHER_ALLOC_HEADER=%x\n",J9MEMTAG_EYECATCHER_ALLOC_HEADER,a);
	printf("J9MEMTAG_EYECATCHER_ALLOC_HEADER=%p,~J9MEMTAG_EYECATCHER_ALLOC_HEADER=%p\n",J9MEMTAG_EYECATCHER_ALLOC_HEADER,a);
	int b = ~J9MEMTAG_EYECATCHER_ALLOC_FOOTER;
	printf("J9MEMTAG_EYECATCHER_ALLOC_FOOTER=%x,~J9MEMTAG_EYECATCHER_ALLOC_FOOTER=%x\n",J9MEMTAG_EYECATCHER_ALLOC_FOOTER,b);
	int c = ~J9MEMTAG_EYECATCHER_FREED_HEADER;
	printf("J9MEMTAG_EYECATCHER_FREED_HEADER=%x,~J9MEMTAG_EYECATCHER_FREED_HEADER=%x\n",J9MEMTAG_EYECATCHER_FREED_HEADER,c);
	int d = ~J9MEMTAG_EYECATCHER_ALLOC_HEADER;
	printf("J9MEMTAG_EYECATCHER_FREED_FOOTER=%x,~J9MEMTAG_EYECATCHER_FREED_FOOTER=%x\n",J9MEMTAG_EYECATCHER_FREED_FOOTER,d);
	printf("callsite=%s\n",J9_GET_CALLSITE());
	printf("callsite=%s\n",CALLSITE());

}
