/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaNativeHelloWorld */
 
#ifndef _Included_JavaNativeHelloWorld
#define _Included_JavaNativeHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaNativeHelloWorld
 * Method:    Nhelloworld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaNativeHelloWorld_Nhelloworld
  (JNIEnv *, jobject);
 
#ifdef __cplusplus
}
#endif
#endif
